name: CI

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Set Node version you use

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test